// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwiyyeusjrbgrnfzsyeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3aXl5ZXVzanJiZ3JuZnpzeWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyMDI3MTMsImV4cCI6MjA1MDc3ODcxM30.7Du5FXDrUr74vVMhKuNSy-DvgfCQHa2Bjhfl55IDf6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);


// lib/supabase/client.ts
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// // Ensure environment variables are defined
// const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
// const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
//   throw new Error('Missing Supabase environment variables');
// }

// // Create and export the Supabase client
// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);